CREATE TABLE `enero` (
  `idenero` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idenero`)
)
ENGINE = InnoDB;


CREATE TABLE `febrero` (
  `idfebrero` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idfebrero`)
)
ENGINE = InnoDB;


CREATE TABLE `marzo` (
  `idmarzo` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idmarzo`)
)
ENGINE = InnoDB;


CREATE TABLE `abril` (
  `idabril` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idabril`)
)
ENGINE = InnoDB;

CREATE TABLE `mayo` (
  `idmayo` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idmayo`)
)
ENGINE = InnoDB;


CREATE TABLE `junio` (
  `idjunio` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idjunio`)
)
ENGINE = InnoDB;


CREATE TABLE `julio` (
  `idjulio` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idjulio`)
)
ENGINE = InnoDB;


CREATE TABLE `agosto` (
  `idagosto` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idagosto`)
)
ENGINE = InnoDB;


CREATE TABLE `septiembre` (
  `idseptiembre` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idseptiembre`)
)
ENGINE = InnoDB;


CREATE TABLE `octubre` (
  `idoctubre` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idoctubre`)
)
ENGINE = InnoDB;


CREATE TABLE `noviembre` (
  `idnoviembre` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`idnoviembre`)
)
ENGINE = InnoDB;


CREATE TABLE `diciembre` (
  `iddiciembre` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT '',
  `tabla` VARCHAR(45) NOT NULL DEFAULT '',
  `usuario` VARCHAR(45) NOT NULL DEFAULT '',
  `fechayhora` DATETIME NOT NULL DEFAULT 0,
  `estacion` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`iddiciembre`)
)
ENGINE = InnoDB;
